# Generated by Django 5.1.6 on 2025-02-20 09:47

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=6, max_length=20, prefix=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idea',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idea',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Friends', 'Friends'), ('Followers', 'Followers')], default='Public', max_length=10),
        ),
        migrations.AlterField(
            model_name='idea',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
