# Generated by Django 5.1.6 on 2025-02-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_active_idea_dislikes_idea_idea_id_idea_likes_and_more'),
        ('notifications', '0002_alter_notification_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ideas.idea'),
        ),
    ]
