# Generated by Django 5.1.6 on 2025-02-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('New Like', 'New Like'), ('New Follow', 'New Follow'), ('New Idea', 'New Idea')], max_length=500),
        ),
    ]
